//tag::ref-doc[]
= CDC Source

https://en.wikipedia.org/wiki/Change_data_capture[Change Data Capture] (CDC) `source` that captures and streams change events from multiple databases.
Currently it supports `MySQL`, `PostgreSQL`, `MongoDB`, `Oracle` and `SQL Server` databases.

It wraps and builds upon the https://debezium.io/docs/embedded/[Debezium Embedded Connector] and provides streaming database changes over arbitrary message binders and thus not be limited to Kafka as the only broker.

== Options

//tag::configuration-properties[]
$$cdc.config$$:: $$Spring pass-trough wrapper for the debezium configuration properties. All properties with 'cdc.config' prefix are converted into Debezium io.debezium.config.Configuration and the prefix is dropped.$$ *($$Map<String, String>$$, default: `$$<none>$$`)*
$$cdc.connector$$:: $$Shortcut for the cdc.config.connector.class property. Either of those can be used as long as they do not contradict with each other.$$ *($$ConnectorType$$, default: `$$<none>$$`, possible values: `mysql`,`postgres`,`mongodb`,`oracle`,`sqlserver`)*
$$cdc.flattering.delete-handling-mode$$:: $$How to handle delete records. Options are: (1) none - records are passed, (2) drop - records are removed and (3) rewrite - adds '__deleted' field to the records.$$ *($$DeleteHandlingMode$$, default: `$$<none>$$`)*
$$cdc.flattering.drop-deletes$$:: $$Drop delete records converted to tombstones records if a processing connector cannot process them or a compaction is undesirable.$$ *($$Boolean$$, default: `$$false$$`)*
$$cdc.flattering.drop-tombstones$$:: $$Debezium by default generates a tombstone record to enable Kafka compaction after a delete record was generated. This record is usually filtered out to avoid duplicates as a delete record is converted to a tombstone record, too.$$ *($$Boolean$$, default: `$$true$$`)*
$$cdc.flattering.enabled$$:: $$Enable flattering the source record events (https://debezium.io/docs/configuration/event-flattening).$$ *($$Boolean$$, default: `$$false$$`)*
$$cdc.include-schema$$:: $$If true the value's schema is included in the outbound message.$$ *($$Boolean$$, default: `$$false$$`)*
$$cdc.offset-storage$$:: $$When a Kafka Connect connector runs, it reads information from the source and periodically records "offsets" that define how much of that information it has processed. Should the connector be restarted, it will use the last recorded offset to know where in the source information it should resume reading.$$ *($$OffsetStorageType$$, default: `$$<none>$$`, possible values: `memory`,`file`,`kafka`,`metadata`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

Build involves two-stages. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps` subfolder. You can then cd into the apps folder:

```
$ cd apps
```
and build all binder projects
```
$ ./mvnw clean package
```

== Testing

The `CDC Source` is based on Debezium, which currently support the following five datastores: `MySQL`, `PostgreSQL`, `MongoDB`, `Oracle` and `SQL Server` databases.

In order to run the `CdcSourceIntegrationTests` integration tests you need to configure source required source databases.

Instructions below explains how to run pre-configured test databases form Docker images.

==== MySQL

Start the `debezium/example-mysql` in a docker:
[source, bash]
----
docker run -it --rm --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=debezium -e MYSQL_USER=mysqluser -e MYSQL_PASSWORD=mysqlpw debezium/example-mysql:0.8
----

Use `mysql` client to connected to the database and to create a `debezium` user with required credentials:
[source, bash]
----
docker run -it --rm --name mysqlterm --link mysql --rm mysql:5.7 sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
mysql> GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium' IDENTIFIED BY 'dbz';
----

Use following properties to connect the CDC Source to the MySQL DB:

[source]
----
cdc.config.offset.flush.interval.ms=60000 # <1>
cdc.config.name=my-sql-connector # <1>
cdc.config.server.id=85744 # <1>
cdc.config.database.server.name=my-app-connector # <1>

cdc.config.connector.class=io.debezium.connector.mysql.MySqlConnector # <2>

cdc.config.database.user=debezium  # <3>
cdc.config.database.password=dbz # <3>
cdc.config.database.hostname=localhost # <3>
cdc.config.database.port=3306 # <3>

cdc.includeSchema=true # <4>
cdc.flattering.enabled=true # <5>
----

<1> Metadata used to identify and dispatch the incoming events.
<2> Configures the CDC Source to use https://debezium.io/docs/connectors/mysql/[MySqlConnector].
<3> Connection to the MySQL server running on `localhost:3306` as `debezium` user.
<4> Includes the https://debezium.io/docs/connectors/mysql/#change-events-value[Change Event Value] schema in the `SourceRecord` events.
<5> Enables the https://debezium.io/docs/configuration/event-flattening/[CDC Event Flattering].

You can run also the `CdcSourceIntegrationTests#CdcMysqlTests` using this mysql configuration.

==== PostgreSQL

psql -U postgres -h localhost -p 5432


Start a pre-configured postgres server from the `debezium/example-postgres:0.8` Docker image:
[source, bash]
----
docker run -it --rm --name postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres debezium/example-postgres:0.8
----

You can connect to this server like this:
[source, bash]
----
psql -U postgres -h localhost -p 5432
----

Use following properties to connect the CDC Source to the PostgreSQL:

[source]
----
cdc.config.offset.flush.interval.ms=60000 # <1>
cdc.config.name=my-sql-connector # <1>
cdc.config.server.id=85744 # <1>
cdc.config.database.server.name=my-app-connector # <1>

cdc.config.connector.class=io.debezium.connector.postgresql.PostgresConnector # <2>

cdc.config.database.user=postgres  # <3>
cdc.config.database.password=postgres # <3>
cdc.config.database..dbname=postgres # <3>
cdc.config.database.hostname=localhost # <3>
cdc.config.database.port=5432 # <3>

cdc.includeSchema=true # <4>
cdc.flattering.enabled=true # <5>
----

<1> Metadata used to identify and dispatch the incoming events.
<2> Configures the CDC Source to use https://debezium.io/docs/connectors/postgresql/[PostgresConnector].
<3> Connection to the PostgreSQL server running on `localhost:5432` as `postgres` user.
<4> Includes the https://debezium.io/docs/connectors/mysql/#change-events-value[Change Event Value] schema in the `SourceRecord` events.
<5> Enables the https://debezium.io/docs/configuration/event-flattening/[CDC Event Flattering].

You can run also the `CdcSourceIntegrationTests#CdcPostgresTests` using this mysql configuration.

==== MongoDB

TODO

==== Oracle (incubator)

TODO

==== SQL Server (incubator)

TODO

== Examples

```
java -jar cdc-source.jar ... use the properties TODO
```

And here is a example pipeline that uses cdc:

```
cdc-stream= TODO
```
