//tag::ref-doc[]
= Debezium Spring Boot Starter

Convenience starter for https://debezium.io[Debezium] integrating  in Spring Boot applications.

https://en.wikipedia.org/wiki/Change_data_capture[Change Data Capture] (CDC) Spring Boot Starter that allows capturing change events from various databases including `MySQL`, `PostgreSQL`, `MongoDB`, `Oracle` and `SQL Server`.

== Quick Start

https://start.spring.io/[Start new Spring Boot project] and add the following starter dependency to activate the CDC:

[source, xml]
----
    <dependency>
        <groupId>org.springframework.cloud.stream.app</groupId>
        <artifactId>cdc-spring-boot-starter</artifactId>
        <version>2.1.0.BUILD-SNAPSHOT</version>
    </dependency>
----

Starter setups an embedded https://debezium.io[Debezium Connector] to capture the database changes.

Implement a `Consumer<SourceRecord>` bean handler to receive and process the CDC notifications:

[source, java]
----
    @Bean
    public Consumer<SourceRecord> mySourceRecordConsumer() {
        return sourceRecord -> {
            System.out.println(" My handler: " + sourceRecord.toString());
        };
    }
----

NOTE: you may have to add `@AutoConfigureBefore(CdcAutoConfiguration.class)` to your Boot class to ensure that your record consumer overrides the default handlers.


All Debezium connector properties supported. Just prefix those properties with `cdc.config` prefix.

Following snipped shows how to configure the https://debezium.io/docs/connectors/mysql/[MySqlConnector] for MySQL database running on localhost:3306
[source]
----
cdc.config.offset.flush.interval.ms=60000
cdc.config.name=my-sql-connector
cdc.config.server.id=85744

cdc.config.database.history=io.debezium.relational.history.MemoryDatabaseHistory
cdc.config.database.server.name=my-app-connector

cdc.config.connector.class=io.debezium.connector.mysql.MySqlConnector
cdc.config.database.user=debezium
cdc.config.database.password=dbz
cdc.config.database.hostname=localhost
cdc.config.database.port=3306
----

Also `cdc.includeSchema` property allows you to include or exclude the value schema from the `SourceRecord` content.
The `cdc.filtering.enabled`, `cdc.filtering.dropTombstones`, `cdc.filtering.dropDeletes` properties to control the https://debezium.io/docs/configuration/event-flattening/[CDC Event Flattering] feature.

The full list of properties:

==== Options

//tag::configuration-properties[]
$$cdc.config$$:: $$Spring pass-trough wrapper for the debezium configuration properties. All properties with 'cdc.config' prefix are converted into Debezium io.debezium.config.Configuration and the prefix is dropped.$$ *($$Map<String, String>$$, default: `$$<none>$$`)*
$$cdc.flattering.delete-handling-mode$$:: $$How to handle delete records. Options are: (1) none - records are passed, (2) drop - records are removed and (3) rewrite - adds '__deleted' field to the records.$$ *($$DeleteHandlingMode$$, default: `$$<none>$$`)*
$$cdc.flattering.drop-deletes$$:: $$Drop delete records converted to tombstones records if a processing connector cannot process them or a compaction is undesirable.$$ *($$Boolean$$, default: `$$false$$`)*
$$cdc.flattering.drop-tombstones$$:: $$Debezium by default generates a tombstone record to enable Kafka compaction after a delete record was generated. This record is usually filtered out to avoid duplicates as a delete record is converted to a tombstone record, too.$$ *($$Boolean$$, default: `$$true$$`)*
$$cdc.flattering.enabled$$:: $$Enable flattering the source record events (https://debezium.io/docs/configuration/event-flattening).$$ *($$Boolean$$, default: `$$false$$`)*
$$cdc.include-schema$$:: $$If true the value's schema is included in the outbound message.$$ *($$Boolean$$, default: `$$false$$`)*
//end::configuration-properties[]

//end::ref-doc[]

